
################################
# ðŸ“¦ OBSIDIAN-LIVESYNC COMPOSE #
################################
# CouchDB backend for Obsidian LiveSync; sync vaults across devices.
# ðŸ”— https://github.com/vrtmrz/obsidian-livesync
################################

services:
  obsidian-livesync:
    image: couchdb:3.3
    container_name: obsidian-livesync
    # user: 1001:1000
    environment:
      - COUCHDB_USER=${DB_USER}
      - COUCHDB_PASSWORD=${DB_PASS}
    volumes:
      - ${PATH_CONFIG}/obsidian-livesync/local.ini:/opt/couchdb/etc/local.ini
      - ${PATH_DATA}/obsidian-livesync:/opt/couchdb/data
    restart: unless-stopped
    networks:
      - proxy
    labels:
#      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      # The Traefik Network
      - "traefik.docker.network=proxy"
      # Don't forget to replace 'obsidian-livesync.example.org' with your own domain
      - "traefik.http.routers.obsidian-livesync.rule=Host(`obsidian-livesync.${DEFAULT_DOMAIN}`)"
      # The 'websecure' entryPoint is basically your HTTPS entrypoint. Check the next code snippet if you are encountering problems only; you probably have a working traefik configuration if this is not your first container you are reverse proxying.
      - "traefik.http.routers.obsidian-livesync.entrypoints=websecure"
      - "traefik.http.routers.obsidian-livesync.service=obsidian-livesync"
      - "traefik.http.services.obsidian-livesync.loadbalancer.server.port=5984"
      - "traefik.http.routers.obsidian-livesync.tls=true"
      # Replace the string 'letsencrypt' with your own certificate resolver
      - "traefik.http.routers.obsidian-livesync.middlewares=obsidiancors"
      # The part needed for CORS to work on Traefik 2.x starts here
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowmethods=GET,PUT,POST,HEAD,DELETE"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowheaders=accept,authorization,content-type,origin,referer"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolalloworiginlist=app://obsidian.md,capacitor://localhost,http://localhost"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolmaxage=3600"
      - "traefik.http.middlewares.obsidiancors.headers.addvaryheader=true"
      - "traefik.http.middlewares.obsidiancors.headers.accessControlAllowCredentials=true"

networks:
  proxy:
    external: true
